#!/bin/sh

setup() {
	FILE=ex02.tar
	GROUP=$(groups $USER | cut -d' ' -f3)
	EXPECT=_out
	OUTPUT=~out
	TMP=./tmp
	echo "drwx--xr-x 2 $USER $GROUP XX Jun 1 20:47 test0" > $EXPECT
	echo "-rwx--xr-- 1 $USER $GROUP 4 Jun 1 21:46 test1" >> $EXPECT
	echo "dr-x---r-- 2 $USER $GROUP XX Jun 1 22:45 test2" >> $EXPECT
	echo "-r-----r-- 2 $USER $GROUP 1 Jun 1 23:44 test3" >> $EXPECT
	echo "-rw-r----x 1 $USER $GROUP 2 Jun 1 23:43 test4" >> $EXPECT
	echo "-r-----r-- 2 $USER $GROUP 1 Jun 1 23:44 test5" >> $EXPECT
	echo "lrwxrwxrwx 1 $USER $GROUP 5 Jun 1 22:20 test6 -> test0" >> $EXPECT
}

print_result() {
	diff --color=auto -U 3 $EXPECT $OUTPUT 2>/dev/null
	[ $? -ne 0 ] && echo "\n""\e[31m[KO]\e[0m fail :-(" && clean
	echo "\e[32m[OK]\e[0m Success :-D" && clean
}

try() {
	test -f $FILE
	[ $? -ne 0 ] && echo "\e[31m[KO]\e[0m $FILE not found :-(" && clean
	tar -xpsf $FILE --one-top-level=$TMP 2>/dev/null
	ls -l $TMP | tr -s ' ' > $OUTPUT
	sed -i '1d' $OUTPUT
	sed -E -i "/^d/s/$GROUP [0-9]+/$GROUP XX/" $OUTPUT
}

clean() {
	rm -rf ex02 $EXPECT $OUTPUT $TMP
	exit 1
}

setup && try && print_result
