#!/bin/sh

setup() {
	FILE=testDay00.tar
	GROUP=$(groups $USER | cut -d' ' -f3)
	TEST="-r--r-xr-x 1 $USER $GROUP 40 Jun 1 23:42 testDay00"
	EXPECT=_out
	OUTPUT=~out
	TMP=tmp
	mkdir -p $TMP
	echo $TEST > $EXPECT
}

print_result() {
	diff --color=auto -U 3 $EXPECT $OUTPUT 2>/dev/null
	[ $? -ne 0 ] && echo """\e[31m[KO]\e[0m fail :-(" && return 0
	echo "\e[32m[OK]\e[0m Success :-D"
}

try() {
	test -f $FILE
	[ $? -ne 0 ] && echo "\e[31m[KO]\e[0m $FILE not found :-(" && clean
	tar --one-top-level=$TMP -xpsf $FILE  2>/dev/null
	ls -l $TMP | tr -s ' ' | sed -e '1d' > $OUTPUT
}

clean() {
	rm -rf $EXPECT $OUTPUT $TMP
	exit 1
}

setup && try && print_result
